Fix node names in the server + Add wait munge.key creation in the execution

diff --git a/openpbs/execution/scripts/run-openpbs b/openpbs/execution/scripts/run-openpbs
--- a/openpbs/execution/scripts/run-openpbs
+++ b/openpbs/execution/scripts/run-openpbs
@@ -1,10 +1,14 @@
-#!/bin/bash
+#!/bin/bash -e
 
 if [ -z "${PBS_SERVER_HOST_NAME}" ]; then
     >&2 echo "Missing environment variable PBS_SERVER_HOST_NAME containing the OpenPBS server hostname"
     exit 1
 fi
 
+if [ ! -f  "/etc/pbs.conf" ]; then
+    >&2 echo "Missing /etc/pbs.conf file"
+    exit 1
+fi
 sed -i "s/__PBS_SERVER_HOST_NAME__/${PBS_SERVER_HOST_NAME}/g" /etc/pbs.conf
 
 source /etc/pbs.conf
